// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1JemK_kgUImuxUYx2wvuoDLEOLppLVUM',
    appId: '1:1017393106231:android:12c5ccf812c8cd67d9deb2',
    messagingSenderId: '1017393106231',
    projectId: 'crud-basico-bc9d3',
    storageBucket: 'crud-basico-bc9d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBS_bcg2DjfEQEh_krQOfWuwUFJKm6B60',
    appId: '1:1017393106231:ios:c679b6e248e52cbcd9deb2',
    messagingSenderId: '1017393106231',
    projectId: 'crud-basico-bc9d3',
    storageBucket: 'crud-basico-bc9d3.appspot.com',
    iosBundleId: 'com.example.firebasecrud',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjQygr5yMXZ_QxQ8gbH-mp-2v9OEWBuaE',
    appId: '1:1017393106231:web:348653abaa167a92d9deb2',
    messagingSenderId: '1017393106231',
    projectId: 'crud-basico-bc9d3',
    authDomain: 'crud-basico-bc9d3.firebaseapp.com',
    storageBucket: 'crud-basico-bc9d3.appspot.com',
    measurementId: 'G-SEMBB1W30F',
  );

}